name: CI CD for Docker Flask App

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        
        - name: Setup Python
          uses: actions/setup-python@v3
        
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flask
            pip install pytest
        
        - name: Run Tests
          run: |
            pytest
    
    build-and-publish:
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME}}
            password: ${{ secrets.DOCKER_PASSWORD}}
        
        - name: Build and push Docker Image
          uses: docker/build-push-action@v4
          with:
            contect: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
        
        - name: Image Digest
          run: echo ${{ steps.build-and-publilsh.outputs.digest }}
